backend:
  name: github
  repo: blip857/sitoEcommerce
  branch: master
  base_url: https://sitoecommerce.pages.dev
  auth_endpoint: /api/auth

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "prodotti"
    label: "Prodotti"
    folder: "src/content/prodotti"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Prezzo", name: "prezzo", widget: "number" }
      - { label: "Immagine", name: "immagine", widget: "image" }